### ISSUE TITLE
DICE

### ISSUE THREAD

**Issue by H-CODE6** [BruceResearch/BiTr-Unet#2]
Hello, your code has been reproduced recently. We can't know the Dice coefficient after the test. How did you get the coefficient

**Comment by BruceResearch** [comment]
Hi, I added a new folder name "evaluation" for you to calculate the Dice score for the validation data. However, this equation for my Dice score may not be the same as that for the BraTS Challenge. If https://www.synapse.org/#!Synapse:syn25829067/wiki/611501 still accepts validation submission, you might want to download the official validation data and upload your segmentation for an official Dice score to evaluate your trained model.

**Comment by H-CODE6** [comment]
Thank you. Can you provide a trained model_ epoch_ last. PTH so that I can reproduce your effect.

**Comment by BruceResearch** [comment]
So you would like me to upload my trained final model?

**Comment by H-CODE6** [comment]
Yes, thank you for your reply.

**Comment by BruceResearch** [comment]
[https://drive.google.com/file/d/13Vom6579mXtt0M3AnXt9pWIlhIDckTMM/view?usp=sharing](url)
I have uploaded the trained model that I submitted for the testing phase of BraTS 2021 on Google Drive. Please unzip it for the pth file.

**Comment by H-CODE6** [comment]
OK, thank you very much for your reply.

**Comment by BruceResearch** [comment]
No problem. Note that this model is trained with all the training data.

**Comment by H-CODE6** [comment]
Have you trained all the data of brats2021? What test set and verification set do you use for testing?

**Comment by BruceResearch** [comment]
Validation data can be downloaded from [https://www.synapse.org/#!Synapse:syn25829067/wiki/611501](url)
However, the segmentation is unavailable for us.
Thus, I need to submit the segmentation image for the website to validate the score for you. That was how I did last year, so I did not need to do the training/validation split. There is a detailed introduction on that website. However, I am not sure if they are still accepting validation requests.

**Comment by H-CODE6** [comment]
OK, thank you for replying to my question. Thank you very much.

**Comment by BruceResearch** [comment]
You are welcome.

**Comment by H-CODE6** [comment]
Hello, author. Do you have a pre training model in the resume when you first started training? Or do you just train to get the model_ epoch_ Last, finally test.

**Comment by BruceResearch** [comment]
https://drive.google.com/file/d/1YAVylEuPz1DDZOTUPdS2YGGYquuOUtYs/view?usp=sharing

Uploaded another model with 1600 epochs, which is the one with the fewest epochs I can possibly find.

**Comment by H-CODE6** [comment]
OK, if I want to train my model, is it running train Py, nothing is filled in the resume, but I find a line of re training prompt when running, and then start training. Does this sentence have any impact? Or the normal operation process?

**Comment by H-CODE6** [comment]
OK, if I want to train my model, is it running train Py, nothing is filled in the resume, but I find a line of re-training prompt when running, and then start training. Does this sentence have any impact? Or the normal operation process?

**Comment by H-CODE6** [comment]
Yes, I want to train my own model. At the beginning, I don't fill in anything in the resume, and finally get my own training model_ epoch_ Last, I wonder if my understanding is correct?

**Comment by H-CODE6** [comment]
Thank you for your answer. Thank you very much. I ran your evaluation code today and found that only WT, TC, mean dice, et and mean hausdorff95 (mm) in your paper can not be evaluated. I wonder if it will take your valuable time to update the evaluation code so that we can better understand the paper and compare the results.

**Comment by H-CODE6** [comment]
OK, thank you very much for your reply. Since I haven't conducted the evaluation on the official brats host again, is it convenient for you to tell me the evaluation process?

**Comment by H-CODE6** [comment]
OK, thank you very much for your answer

**Comment by H-CODE6** [comment]
Hello, data postprocessing cannot run successfully after the test. Can you tell me which parameters to change in the code? Or download those files?

**Comment by BruceResearch** [comment]
The performance of the method of connected_components.py is not ideal after experiments, and in my paper we use majority voting only. Thus, please just run ensemble_by_majority_voting.py as your post process procedure. You need to specify test_path (main folder where stores segmentation outputs from each model) and model_list(specific folder names of each model's outputs). When running ensemble_by_majority_voting.py, specify the method, which is" python ensemble_by_majority_voting.py --m 0"

**Comment by H-CODE6** [comment]
Excuse me, model_ list is the specific folder name of each model output you refer to on the list?  I only generated a model on the checkpoint epoch_ last. pth ，and other files, as well as the above result_ path，pred_ path，prob_ Does path need to be modified?

**Comment by BruceResearch** [comment]
You can not do the ensemble with only one model. You have to generate several sets of outputs from different models to do the ensemble.

**Comment by H-CODE6** [comment]
Well, thank you very much.

**Comment by H-CODE6** [comment]
Hello, what is the best effect of your final experimental results? What are the dice and other coefficients respectively? I want to compare it with the results I reproduced.

**Comment by BruceResearch** [comment]
Please refer to Table 1 in the paper : https://arxiv.org/pdf/2109.12271.pdf

**Comment by H-CODE6** [comment]
Yes, I have read your paper completely and am interested in the coefficients of Table 2 and table 3. How do you realize it?

**Comment by BruceResearch** [comment]
Those summary statistics are provided and calculated by the BraTS official validation result.

**Comment by BruceResearch** [comment]
We still mainly look at the mean result. My table 2 and table 3 provide other summary statistics, which only serve as a supplementary perspective of evaluating the performance.

**Comment by H-CODE6** [comment]
OK, thank you very much for your answer

**Comment by H-CODE6** [comment]
Hello, I just used Dual_focal_loss in the loss function， The performance test of the loss function shows that the image background of the final test output is blue, and the test result is not very normal. Do you want to modify the code when using other loss functions.

**Comment by H-CODE6** [comment]
Hello, author. I've been studying your code recently, at bitrunet.py Some of  are not very clear. Can you comment on the specific functions in front of each function and class? So that our readers can better understand the paper.

**Comment by BruceResearch** [comment]
Hi, Sorry I have been very busy these days. I have added some comments for each class to illustrate their roles. The main idea is just that I define the encoder class and decoder class separately, and finally, combine them in one def.

**Comment by H-CODE6** [comment]
OK, thank you very much for your reply to me in your busy schedule. I would like to express my deep gratitude to you again.

**Comment by H-CODE6** [comment]
Hello, after using your evaluation file, it is found that ET performance cannot be evaluated. Can you update the code to facilitate our evaluation? We look forward to your reply.

**Comment by BruceResearch** [comment]
I see where the problem is. It should be fixed now. Please let me know if it works.

**Comment by H-CODE6** [comment]
OK, thank you very much. I'll give you feedback immediately after my evaluation. Thank you again

**Comment by BruceResearch** [comment]
Just updated again, found a typo

**Comment by H-CODE6** [comment]
The following error occurred

Traceback (most recent call last):
  File "evaluation.py", line 90, in <module>
    dice = dice_of_brats_data_set(gt_names, seg_names, type_idx)
  File "evaluation.py", line 55, in dice_of_brats_data_set
    s_volume[s_volume == 2 or s_volume ==1] = 0
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by BruceResearch** [comment]
what about now

**Comment by H-CODE6** [comment]
It can be run. At that time, the final result of the same data WT and TC is very different from that of the code that has not been updated before

**Comment by H-CODE6** [comment]
now：
tissue type ET
dice mean   [0.83201768]
dice std    [0.23055119]
tissue type WT
dice mean   [0.80649212]
dice std    [0.1666985]
tissue type TC
dice mean   [0.71619503]
dice std    [0.28385196]

old：
tissue type whole
dice mean   [0.90952711]
dice std    [0.10472148]
tissue type core
dice mean   [0.88381648]
dice std    [0.18333644]
tissue type all
tissue label [1, 2, 3, 4]
dice mean   [0.71619503 0.80649212 1.         0.83201768]
dice std    [0.28385196 0.1666985  0.         0.23055119]

**Comment by BruceResearch** [comment]
That is right, the old code is totally wrong for the tumor label since I actually did not use them at all.  Based on the info on BraTS website, "Annotations comprise the GD-enhancing tumor (ET — label 4), the peritumoral edematous/invaded tissue (ED — label 2), and the necrotic tumor core (NCR — label 1)", I modified the code.

**Comment by BruceResearch** [comment]
I see, it can still be changed, give me a minute.

**Comment by BruceResearch** [comment]
updated

**Comment by H-CODE6** [comment]
No problem. Can you tell me why

**Comment by BruceResearch** [comment]
Based on the info on BraTS website, "Annotations comprise the GD-enhancing tumor (ET — label 4), the peritumoral edematous/invaded tissue (ED — label 2), and the necrotic tumor core (NCR — label 1)"

Plus,
WT consists of enhancing components, nonenhancing components including necrosis, and edema (ET + NCR + ED). TC consists of enhancing components and nonenhancing components including necrosis (ET + NCR).

Thus, we also need to combine those.

**Comment by H-CODE6** [comment]
OK, do you have any codes to evaluate Hausdorff distance, sensitivity and specificity? These indicators are also very important.

**Comment by BruceResearch** [comment]
Writing them for u now

**Comment by H-CODE6** [comment]
ok, thank you very much

**Comment by BruceResearch** [comment]
Updated, it may contain bug since I can't test it out now, but everything you need is there.

**Comment by H-CODE6** [comment]
OK, I'll test it and give you feedback right away

**Comment by H-CODE6** [comment]
raceback (most recent call last):
  File "evaluation.py", line 257, in <module>
    np.savetxt(s_folder + '/Hausdorff_distance_{0:}.txt'.format(test_type), hd)
  File "<__array_function__ internals>", line 6, in savetxt
  File "/home/hkw/anaconda3/envs/pytorch/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1381, in savetxt
    "Expected 1D or 2D array, got %dD array instead" % X.ndim)
ValueError: Expected 1D or 2D array, got 0D array instead

**Comment by BruceResearch** [comment]
No need to save it actually，you may delete this line

**Comment by BruceResearch** [comment]
Found another error in distance computation， I'll fix it tomorrow

**Comment by H-CODE6** [comment]
OK, I look forward to your repair. The running time of the file is very long. I don't know whether there are still problems. I'll give you feedback in time.

**Comment by BruceResearch** [comment]
distance computation for large array is time consuming.

**Comment by H-CODE6** [comment]
OK, I look forward to your repair tomorrow, and I will communicate with you in time.

**Comment by H-CODE6** [comment]
tissue type ET
dice mean   [0.83201768]
dice std    [0.23055119]
sensitivity   [0.9673336653678258]
specificity   [0.9996706719360656]
Hausdorff_distance   21.02379604162864
Traceback (most recent call last):
  File "evaluation.py", line 250, in <module>
    sensitivity = sensitivity_of_brats_data_set(gt_names, seg_names, type_idx)
  File "evaluation.py", line 182, in sensitivity_of_brats_data_set
    temp_sensi = sensitivity_whole(s_volume,g_volume)
  File "evaluation.py", line 41, in sensitivity_whole
    return sensitivity(seg>0,ground>0)
TypeError: 'list' object is not callable

The results just came out are only et, and the other two items cannot be displayed

**Comment by BruceResearch** [comment]
It is updated and tested. Dice and Hausodorff distance should be good now. For sensitivity and specificity, I tried several ways and couldn't resolve the error. I would say just looking at Dice and Hausodorff distance is sufficient as they are the official metrics of BraTS. You are welcome to debug yourself to solve the error of sensitivity and specificity.

**Comment by H-CODE6** [comment]
ok, thank you very much

**Comment by H-CODE6** [comment]
Hello, author. After a lot of tests, I found Hausdorff_ Distance coefficient is always the same in two of ET, TC and wt. I don't know why?

**Comment by H-CODE6** [comment]
1.
tissue type ET
dice mean   [0.88853114]
dice std    [0.1029538]
Hausdorff_distance   15.165750888103101
tissue type WT
dice mean   [0.91242634]
dice std    [0.06855426]
Hausdorff_distance   6.4031242374328485
tissue type TC
dice mean   [0.91720559]
dice std    [0.12459188]
Hausdorff_distance   15.165750888103101

2.
dice mean   [0.83913826]
dice std    [0.20701617]
Hausdorff_distance   5.0
tissue type WT
dice mean   [0.90823157]
dice std    [0.08411381]
Hausdorff_distance   3.1622776601683795
tissue type TC
dice mean   [0.90465758]
dice std    [0.14383377]
Hausdorff_distance   5.0

3.
tissue type ET
dice mean   [0.83201768]
dice std    [0.23055119]
Hausdorff_distance   5.744562646538029
tissue type WT
dice mean   [0.90952711]
dice std    [0.10472148]
Hausdorff_distance   14.071247279470288
tissue type TC
dice mean   [0.88381648]
dice std    [0.18333644]
Hausdorff_distance   14.071247279470288

**Comment by BruceResearch** [comment]
try now

**Comment by H-CODE6** [comment]
Hello, author. After testing, I found Hausdorff_ Distance is different from the previous code results. Can you explain the principle?

**Comment by BruceResearch** [comment]
instead of differentiating wt, et,tc in the function of  hd_of_brats_data_set(), I now wrote separate def hausdorff_whole (),def hausdorff_en (), def hausdorff_whole (),hausdorff_core() to calculate HD for wt, et,tc. 
Note that the way of differentiating ET for calculating HD is different from calculating Dice, which is why I was wrong last time. For calculating HD for ET, we want Hausdorff_distance(seg!=4,ground!=4), for calculating Dice for ET, we want binary_dice3d(s_volume ==4, g_volume  ==4). I realized this by reading "https://github.com/Issam28/Brain-tumor-segmentation/blob/master/evaluation_metrics.py" did so, but I don't know why.  You should do really more research to ascertain this or by adopting other trustworthy sources of codes.

**Comment by H-CODE6** [comment]
Well, thank you very much.

**Comment by H-CODE6** [comment]
Hello, I found the minimum batch size in train.py can only be set to 4. I wonder if there is a way to set it to 2 or 1

**Comment by BruceResearch** [comment]
What I had done for random cropping is the most conventional way. Since BraTS training data is well-crafted (ROIs locate in the center of the image), even though I can't guarantee that no voxel of ROI is cropped, I would say it is safe to do so. However, testing data may be more wild and diverse, and cropping of data augmentation is an open research area where you can develop your idea and be creative to do fancier tricks, which can also be the selling point of your paper. Thus, you may want to import more advanced cropping tricks.

**Comment by H-CODE6** [comment]
OK, thank you very much

**Comment by H-CODE6** [comment]
Hello, I am sorry to disturb you again. Recently, I was working on the dataset and needed to process all brats2021 data into 128*128*128 in advance. I haven't found any code that can be used directly. I wonder if you have any codes in this area. Thank you very much for your help

**Comment by BruceResearch** [comment]
monai.transforms.SpatialCrop： 
General purpose cropper to produce sub-volume region of interest (ROI). If a dimension of the expected ROI size is bigger than the input image size, will not crop that dimension. So the cropped result may be smaller than the expected ROI, and the cropped results of several images may not have exactly the same shape. It can support to crop ND spatial (channel-first) data.

[https://docs.monai.io/en/stable/transforms.html#transform](url)

**Comment by H-CODE6** [comment]
Thank you very much for your reply. I read all your codes and know your brats Py is the pruning code, which is called in the train. I want to directly use your code to prune the brats data into 128*128*128, but it has not been successfully implemented. I wonder if you have time to help me. The first step is to prune all the data, and then perform preprocessing, training, etc.

**Comment by H-CODE6** [comment]
I want to cut all the data into 128*128*128 sizes in the first step, and then carry out subsequent training and other operations, which have not been successfully realized. I look forward to your help. Thank you very much
